server:
  port: 9090
spring:
  application:
    name: kjxz-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dafei-nb/config.git

eureka:
  instance:
    hostname: config
  client:
    service-url:
      #指定要去注册的地址
      defaultZone: http://e1:8000/eureka
